version: 2.0
jobs:
 build:
   docker:
     - image: circleci/node:10-browsers
   steps:
     - checkout
     - run:
         name: Install packages
         command: |
           npm install
     - run:
         name: Running Test Suite
         command: |
           npm test
     - store_artifacts:
          path: output
